---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live-storage-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ or .LiveSize "5Gi" }}
  hostPath:
    path: {{ or .LivePath "/opt/weaver/block-node-storage/live" }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: live-storage-pvc
  namespace: {{ or .Namespace "block-node" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ or .LiveSize "5Gi" }}
  volumeName: live-storage-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: archive-storage-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ or .ArchiveSize "5Gi" }}
  hostPath:
    path: {{ or .ArchivePath "/opt/weaver/block-node-storage/archive" }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archive-storage-pvc
  namespace: {{ or .Namespace "block-node" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ or .ArchiveSize "5Gi" }}
  volumeName: archive-storage-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-storage-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ or .LogSize "5Gi" }}
  hostPath:
    path: {{ or .LogPath "/opt/weaver/block-node-storage/logs" }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-storage-pvc
  namespace: {{ or .Namespace "block-node" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ or .LogSize "5Gi" }}
  volumeName: logging-storage-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: verification-storage-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ or .VerificationSize "5Gi" }}
  hostPath:
    path: {{ or .VerificationPath "/opt/weaver/block-node-storage/verification" }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verification-storage-pvc
  namespace: {{ or .Namespace "block-node" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ or .VerificationSize "5Gi" }}
  volumeName: verification-storage-pv
