---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live-storage-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /opt/weaver/block-node-storage/live
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: live-storage-pvc
  namespace: block-node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: live-storage-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: archive-storage-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /opt/weaver/block-node-storage/archive
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archive-storage-pvc
  namespace: block-node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: archive-storage-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-storage-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /opt/weaver/block-node-storage/logs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-storage-pvc
  namespace: block-node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: logging-storage-pv
